CREATE TABLE `government_accountability` (
	`id` int AUTO_INCREMENT NOT NULL,
	`official_name` varchar(255) NOT NULL,
	`title` varchar(255) NOT NULL,
	`government_level` enum('federal','provincial','municipal','agency','other') NOT NULL,
	`department` varchar(255),
	`jurisdiction` varchar(255),
	`email` varchar(320),
	`phone` varchar(20),
	`office_address` text,
	`social_media` text,
	`website` varchar(512),
	`date_first_contacted` timestamp,
	`contact_method` enum('email','phone','social_media','in_person','letter','other'),
	`response_status` enum('no_response','acknowledged','committed','acting','hostile','cease_and_desist') NOT NULL DEFAULT 'no_response',
	`response_date` timestamp,
	`response_content` text,
	`commitment_details` text,
	`follow_up_date` timestamp,
	`cease_and_desist_received` enum('yes','no') NOT NULL DEFAULT 'no',
	`cease_and_desist_date` timestamp,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `government_accountability_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `orange_shirt_accountability` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organization_name` varchar(255) NOT NULL,
	`organization_type` enum('corporate_sponsor','nhl_team','sports_team','orange_shirt_society','other') NOT NULL,
	`category` varchar(100),
	`email` varchar(320),
	`phone` varchar(20),
	`social_media` text,
	`website` varchar(512),
	`contact_person` varchar(255),
	`date_first_contacted` timestamp,
	`contact_method` enum('email','phone','social_media','in_person','letter','other'),
	`response_status` enum('no_response','acknowledged','committed','acting','performative','hostile') NOT NULL DEFAULT 'no_response',
	`response_date` timestamp,
	`response_content` text,
	`commitment_details` text,
	`follow_up_date` timestamp,
	`notes` text,
	`is_performative` enum('yes','no') NOT NULL DEFAULT 'no',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orange_shirt_accountability_id` PRIMARY KEY(`id`)
);
